// Auto-generated by Steam Workshop Publisher Tool on first upload.
// This file gets the publishedid filled in once the mod has been pushed to
// the Workshop. Until then this is a placeholder so the directory layout is
// recognised by build tools.

protocol = 1;
publishedid = 0;
name = "Takaro Integration (Server)";
timestamp = 0;
